image: registry.gitlab.fpcomplete.com/fpco/default-build-image:1210

variables:
  # the branch is the "channel" that new versions are released to
  # change to ${CI_COMMIT_REF_SLUG} when CI is updated
  CHANNEL: "${CI_BUILD_REF_SLUG}"

stages:
  - release

release:
  stage: release
  only:
    - branches
  script:
    # build ID is the default version, use git tag when building a tag
    # change to ${CI_COMMIT_SHA} when CI is updated
    - "VERSION=${CI_BUILD_REF:0:7}-${CI_PIPELINE_ID} make release-all"

release-tag:
  stage: release
  variables:
    CHANNEL: release
    # change to ${CI_COMMIT_TAG} when CI is updated
    VERSION: "${CI_BUILD_TAG}"
  only:
    - tags
  script:
    - "make release-all"
